"""add phone_number into user_database table

Revision ID: ab635599ca85
Revises: e34c117d82d1
Create Date: 2023-02-12 17:20:35.049918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab635599ca85'
down_revision = 'e34c117d82d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_database', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_database', 'phone_number')
    # ### end Alembic commands ###
